name: checkin

on:

  schedule:
  - cron: 0 16 * * * 

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
            
      - name: Run checkin
        env:
            COOKIE1: ${{ secrets.COOKIE1 }}
            COOKIE2: ${{ secrets.COOKIE2 }}
            COOKIE3: ${{ secrets.COOKIE3 }}
        run: python3 ./main.py
